# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colouring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourpicture',
            name='outline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colouring.OutlinePicture'),
        ),
    ]
